### PR TITLE
Added CustomData box content in host detail page

### PR DESCRIPTION
**Pull request by amreo**
Fixes https://github.com/ercole-io/ercole/issues/426

@rcmaiolini I don't known how to remove the beginning spaces of preformatted texts. Can you advice me how to fix the issue? Or how to add a json tree view like http://jsonviewer.stack.hu/ ?

Schermata del 2020-10-01 01-03-29

### CODE REVIEW

**Comment by amreo** [comment]
Noooo

**Comment by cirelli94** [comment]
Don't worry: `ercole-io:2.0` became `ercole-io:master`

**Comment by amreo** [comment]
And the PR?

**Comment by cirelli94** [comment]
As I replied in https://github.com/ercole-io/ercole/issues/426 , this PR is a little bit out of the actual focus and goal of Ercole!

**Pull request closed without merging**
